#!/bin/bash
ttrss_repo="https://tt-rss.org/git/tt-rss.git"

# Deploy Tiny Tiny RSS from Git repo...
ttrss_dir="${OPENSHIFT_DATA_DIR}ttrss"
echo "ttrss_dir=$ttrss_dir"
: [ ! -d "${ttrss_dir}" ] && exit 0
git clone "${ttrss_repo}" "${ttrss_dir}"


