#!/bin/bash

# Deploy Tiny Tiny RSS
ttrss_current="${OPENSHIFT_DATA_DIR}tt-rss"
ttrss_root="${OPENSHIFT_REPO_DIR}php/tt-rss"
ttrss_config="${OPENSHIFT_REPO_DIR}.openshift/config/tt-rss.php"
ttrss_htaccess="${OPENSHIFT_REPO_DIR}.openshift/config/tt-rss.htaccess"

[ -d "${ttrss_root}" ] && rm -rf "${ttrss_root}"
mkdir "${ttrss_root}"
cp -a "${ttrss_current}"/* "${ttrss_root}"
chmod -R 777 "${ttrss_root}"/{cache,lock,feed-icons}

[ -f "${ttrss_config}" ] && cp "${ttrss_config}" "${ttrss_root}"/config.php
[ -f "${ttrss_htaccess}" ] && cp "${ttrss_htaccess}" "${ttrss_root}"/.htaccess

